// <auto-generated />
using System;
using Infrastructure.Foundation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531172056_DbSeed")]
    partial class DbSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Property", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ул. Тверская, 10",
                            City = "Москва",
                            Country = "Россия",
                            Latitude = 55.759999999999998,
                            Longitude = 37.619999999999997,
                            Name = "Grand Plaza Hotel"
                        },
                        new
                        {
                            Id = 2,
                            Address = "ул. Приморская, 25",
                            City = "Сочи",
                            Country = "Россия",
                            Latitude = 43.590000000000003,
                            Longitude = 39.729999999999997,
                            Name = "Seaside Resort"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Альпийская ул., 5",
                            City = "Красная Поляна",
                            Country = "Россия",
                            Latitude = 43.68,
                            Longitude = 40.200000000000003,
                            Name = "Mountain Lodge"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Невский пр., 50",
                            City = "Санкт-Петербург",
                            Country = "Россия",
                            Latitude = 59.93,
                            Longitude = 30.32,
                            Name = "City Inn"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GuestPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsCanceled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Reservation", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<decimal>("DailyPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MaxPersonCount")
                        .HasColumnType("int");

                    b.Property<int>("MinPersonCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRoomsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("RoomType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenities = "AirConditioning,TV,Hairdryer",
                            Currency = 0,
                            DailyPrice = 5000m,
                            MaxPersonCount = 2,
                            MinPersonCount = 1,
                            Name = "Standard",
                            PropertyId = 1,
                            Services = "WiFi,Breakfast",
                            TotalRoomsCount = 20
                        },
                        new
                        {
                            Id = 2,
                            Amenities = "AirConditioning,TV,MiniBar,Bathtub",
                            Currency = 0,
                            DailyPrice = 8000m,
                            MaxPersonCount = 3,
                            MinPersonCount = 1,
                            Name = "Deluxe",
                            PropertyId = 1,
                            Services = "WiFi,Breakfast,Gym,Spa",
                            TotalRoomsCount = 10
                        },
                        new
                        {
                            Id = 3,
                            Amenities = "AirConditioning,TV,MiniBar,Safe,Balcony,Bathtub,CoffeeMaker",
                            Currency = 0,
                            DailyPrice = 15000m,
                            MaxPersonCount = 4,
                            MinPersonCount = 1,
                            Name = "Suite",
                            PropertyId = 1,
                            Services = "WiFi,Breakfast,Gym,Spa,RoomService,Concierge",
                            TotalRoomsCount = 5
                        },
                        new
                        {
                            Id = 4,
                            Amenities = "AirConditioning,TV,Hairdryer",
                            Currency = 0,
                            DailyPrice = 3000m,
                            MaxPersonCount = 2,
                            MinPersonCount = 1,
                            Name = "Standard",
                            PropertyId = 2,
                            Services = "WiFi,Breakfast,Parking",
                            TotalRoomsCount = 30
                        },
                        new
                        {
                            Id = 5,
                            Amenities = "AirConditioning,TV,MiniBar,Balcony",
                            Currency = 0,
                            DailyPrice = 5000m,
                            MaxPersonCount = 4,
                            MinPersonCount = 2,
                            Name = "Family Room",
                            PropertyId = 2,
                            Services = "WiFi,Breakfast,Parking,Laundry",
                            TotalRoomsCount = 15
                        },
                        new
                        {
                            Id = 6,
                            Amenities = "AirConditioning,TV,Hairdryer",
                            Currency = 0,
                            DailyPrice = 4000m,
                            MaxPersonCount = 2,
                            MinPersonCount = 1,
                            Name = "Standard",
                            PropertyId = 3,
                            Services = "WiFi,Breakfast,Parking",
                            TotalRoomsCount = 10
                        },
                        new
                        {
                            Id = 7,
                            Amenities = "AirConditioning,TV,MiniBar,Balcony,Bathtub,CoffeeMaker",
                            Currency = 0,
                            DailyPrice = 12000m,
                            MaxPersonCount = 6,
                            MinPersonCount = 1,
                            Name = "Chalet",
                            PropertyId = 3,
                            Services = "WiFi,Breakfast,Parking",
                            TotalRoomsCount = 5
                        },
                        new
                        {
                            Id = 8,
                            Amenities = "AirConditioning,TV,Hairdryer",
                            Currency = 0,
                            DailyPrice = 2500m,
                            MaxPersonCount = 2,
                            MinPersonCount = 1,
                            Name = "Standard",
                            PropertyId = 4,
                            Services = "WiFi,Breakfast",
                            TotalRoomsCount = 15
                        },
                        new
                        {
                            Id = 9,
                            Amenities = "AirConditioning,TV,MiniBar,CoffeeMaker",
                            Currency = 0,
                            DailyPrice = 4000m,
                            MaxPersonCount = 2,
                            MinPersonCount = 1,
                            Name = "Business Room",
                            PropertyId = 4,
                            Services = "WiFi,Breakfast,Laundry,Gym",
                            TotalRoomsCount = 8
                        });
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Domain.Entities.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.RoomType", null)
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.RoomType", b =>
                {
                    b.HasOne("Domain.Entities.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
