// <auto-generated />
using System;
using Infrastructure.Foundation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612122041_IndexAndPkNaming")]
    partial class IndexAndPkNaming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_property");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("country");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_property");

                    b.ToTable("Property", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ул. Тверская, 10",
                            City = "Москва",
                            Country = "Россия",
                            Latitude = 55.759999999999998,
                            Longitude = 37.619999999999997,
                            Name = "Grand Plaza Hotel"
                        },
                        new
                        {
                            Id = 2,
                            Address = "ул. Приморская, 25",
                            City = "Сочи",
                            Country = "Россия",
                            Latitude = 43.590000000000003,
                            Longitude = 39.729999999999997,
                            Name = "Seaside Resort"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Альпийская ул., 5",
                            City = "Красная Поляна",
                            Country = "Россия",
                            Latitude = 43.68,
                            Longitude = 40.200000000000003,
                            Name = "Mountain Lodge"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Невский пр., 50",
                            City = "Санкт-Петербург",
                            Country = "Россия",
                            Latitude = 59.93,
                            Longitude = 30.32,
                            Name = "City Inn"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reservation");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ArrivalDate")
                        .HasColumnType("date")
                        .HasColumnName("arrival_date");

                    b.Property<TimeOnly>("ArrivalTime")
                        .HasColumnType("time")
                        .HasColumnName("arrival_time");

                    b.Property<int>("Currency")
                        .HasColumnType("int")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("date")
                        .HasColumnName("departure_date");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time")
                        .HasColumnName("departure_time");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("guest_name");

                    b.Property<string>("GuestPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("guest_phone_number");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit")
                        .HasColumnName("is_canceled");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("id_property");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_roomtype");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_reservation");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_reservation_property_id");

                    b.HasIndex("RoomTypeId", "PropertyId")
                        .HasDatabaseName("IX_Reservation_RoomTypeId_PropertyId");

                    b.ToTable("Reservation", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_roomtype");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("amenities");

                    b.Property<int>("Currency")
                        .HasColumnType("int")
                        .HasColumnName("currency");

                    b.Property<decimal>("DailyPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("daily_price");

                    b.Property<int>("MaxPersonCount")
                        .HasColumnType("int")
                        .HasColumnName("max_person_count");

                    b.Property<int>("MinPersonCount")
                        .HasColumnType("int")
                        .HasColumnName("min_person_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("id_property");

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("services");

                    b.Property<int>("TotalRoomsCount")
                        .HasColumnType("int")
                        .HasColumnName("total_rooms_count");

                    b.HasKey("Id")
                        .HasName("pk_room_type");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("IX_RoomType_PropertyId");

                    b.ToTable("RoomType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenities = "0,1,7",
                            Currency = 0,
                            DailyPrice = 5000m,
                            MaxPersonCount = 2,
                            MinPersonCount = 1,
                            Name = "Standard",
                            PropertyId = 1,
                            Services = "1,0",
                            TotalRoomsCount = 20
                        },
                        new
                        {
                            Id = 2,
                            Amenities = "0,1,2,5",
                            Currency = 0,
                            DailyPrice = 8000m,
                            MaxPersonCount = 3,
                            MinPersonCount = 1,
                            Name = "Deluxe",
                            PropertyId = 1,
                            Services = "1,0,5,6",
                            TotalRoomsCount = 10
                        },
                        new
                        {
                            Id = 3,
                            Amenities = "0,1,2,3,4,5,6",
                            Currency = 0,
                            DailyPrice = 15000m,
                            MaxPersonCount = 4,
                            MinPersonCount = 1,
                            Name = "Suite",
                            PropertyId = 1,
                            Services = "1,0,5,6,7,8",
                            TotalRoomsCount = 5
                        },
                        new
                        {
                            Id = 4,
                            Amenities = "0,1,7",
                            Currency = 0,
                            DailyPrice = 3000m,
                            MaxPersonCount = 2,
                            MinPersonCount = 1,
                            Name = "Standard",
                            PropertyId = 2,
                            Services = "1,0,2",
                            TotalRoomsCount = 30
                        },
                        new
                        {
                            Id = 5,
                            Amenities = "0,1,2,4",
                            Currency = 0,
                            DailyPrice = 5000m,
                            MaxPersonCount = 4,
                            MinPersonCount = 2,
                            Name = "Family Room",
                            PropertyId = 2,
                            Services = "1,0,2,4",
                            TotalRoomsCount = 15
                        },
                        new
                        {
                            Id = 6,
                            Amenities = "0,1,7",
                            Currency = 0,
                            DailyPrice = 4000m,
                            MaxPersonCount = 2,
                            MinPersonCount = 1,
                            Name = "Standard",
                            PropertyId = 3,
                            Services = "1,0,2",
                            TotalRoomsCount = 10
                        },
                        new
                        {
                            Id = 7,
                            Amenities = "0,1,2,4,5,6",
                            Currency = 0,
                            DailyPrice = 12000m,
                            MaxPersonCount = 6,
                            MinPersonCount = 1,
                            Name = "Chalet",
                            PropertyId = 3,
                            Services = "1,0,2",
                            TotalRoomsCount = 5
                        },
                        new
                        {
                            Id = 8,
                            Amenities = "0,1,7",
                            Currency = 0,
                            DailyPrice = 2500m,
                            MaxPersonCount = 2,
                            MinPersonCount = 1,
                            Name = "Standard",
                            PropertyId = 4,
                            Services = "1,0",
                            TotalRoomsCount = 15
                        },
                        new
                        {
                            Id = 9,
                            Amenities = "0,1,2,6",
                            Currency = 0,
                            DailyPrice = 4000m,
                            MaxPersonCount = 2,
                            MinPersonCount = 1,
                            Name = "Business Room",
                            PropertyId = 4,
                            Services = "1,0,4,5",
                            TotalRoomsCount = 8
                        });
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Domain.Entities.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_property_property_id");

                    b.HasOne("Domain.Entities.RoomType", null)
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_room_type_room_type_id");
                });

            modelBuilder.Entity("Domain.Entities.RoomType", b =>
                {
                    b.HasOne("Domain.Entities.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_type_property_property_id");
                });
#pragma warning restore 612, 618
        }
    }
}
